userAgent: "Mozilla/5.0 (X11; Linux x86_64{randomInt}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36{randomInt}"
products:
  Amazon:
    # RTX 3080
    - Name: ASUS TUF Gaming NVIDIA GeForce RTX 3080
      Url: https://amazon.com/dp/B08HHDP9DW
    - Url: https://amazon.com/ASUS-Graphics-DisplayPort-Military-Grade-Certification/dp/B08HH5WF97
    - Url: https://amazon.com/PNY-GeForce-Gaming-Epic-X-Graphics/dp/B08HBR7QBM
    - Url: https://amazon.com/PNY-GeForce-Gaming-Epic-X-Graphics/dp/B08HBTJMLJ
    - Url: https://amazon.com/MSI-GeForce-RTX-3080-10G/dp/B08HR5SXPS
    - Url: https://amazon.com/MSI-GeForce-RTX-3080-10G/dp/B08HR7SV3M
    - Url: https://amazon.com/EVGA-10G-P5-3897-KR-GeForce-Technology-Backplate/dp/B08HR3Y5GQ
    - Url: https://amazon.com/EVGA-10G-P5-3895-KR-GeForce-Technology-Backplate/dp/B08HR3DPGW
    - Url: https://amazon.com/EVGA-10G-P5-3885-KR-GeForce-Cooling-Backplate/dp/B08HR55YB5
    - Url: https://amazon.com/EVGA-10G-P5-3883-KR-GeForce-Cooling-Backplate/dp/B08HR4RJ3Q
    - Url: https://amazon.com/EVGA-10G-P5-3881-KR-GeForce-GAMING-Cooling/dp/B08HR6FMF3
    - Url: https://amazon.com/GIGABYTE-GeForce-Graphics-WINDFORCE-GV-N3080GAMING/dp/B08HJTH61J
    - Url: https://amazon.com/GIGABYTE-GeForce-Graphics-WINDFORCE-GV-N3080EAGLE/dp/B08HJS2JLJ
    # RTX 3090
    # - Url: https://amazon.com/PNY-GeForce-Gaming-Epic-X-Graphics/dp/B08HBQWBHH
    # - Url: https://amazon.com/PNY-GeForce-RTX-3090-Graphics/dp/B08HBVX53D
    # - Url: https://amazon.com/MSI-GeForce-RTX-3090-24G/dp/B08HRBW6VB
    # - Url: https://amazon.com/MSI-GeForce-384-Bit-Architecture-Graphics/dp/B08HR9D2JS
    # - Url: https://amazon.com/GIGABYTE-GeForce-Graphics-WINDFORCE-GV-N3090GAMING/dp/B08HJRF2CN
    # - Url: https://amazon.com/GIGABYTE-GeForce-Graphics-WINDFORCE-GV-N3090EAGLE/dp/B08HJPDJTY
    # - Url: https://amazon.com/ASUS-Graphics-DisplayPort-Military-Grade-Certification/dp/B08HJGNJ81
    # - Url: https://amazon.com/ASUS-Graphics-DisplayPort-Military-Grade-Certification/dp/B08HJLLF7G
    # RTX 3070
    - Url: https://amazon.com/dp/B08L8LG4M3
    - Url: https://amazon.com/dp/B08LW46GH2
    - Url: https://amazon.com/ASUS-Graphics-DisplayPort-Axial-tech-2-9-Slot/dp/B08L8JNTXQ
    - Url: https://www.amazon.com/PNY-GeForce-Gaming-Epic-X-Graphics/dp/B08HBJB7YD
    - Url: https://www.amazon.com/ZOTAC-Graphics-IceStorm-Advanced-ZT-A30700H-10P/dp/B08LF1CWT2
    - Url: https://www.amazon.com/MSI-GeForce-256-Bit-Architecture-Graphics/dp/B08KWLMZV4
    - Url: https://www.amazon.com/Gigabyte-Graphics-WINDFORCE-GV-N3070GAMING-OC-8GD/dp/B08KY266MG
    - Url: https://www.amazon.com/MSI-GeForce-RTX-3070-Architecture/dp/B08KWN2LZG
  # NewEgg is not implemented yet...
  # NewEgg:
  #   - Url: https://www.newegg.com/msi-geforce-rtx-3090-rtx-3090-ventus-3x-24g/p/N82E16814137599
  #   - Name: EVGA GeForce RTX 3090 FTW3 GAMING
  #     Url: https://www.newegg.com/evga-geforce-rtx-3090-24g-p5-3985-kr/p/N82E16814487525
